---
title: "Introduction"
author: "Jessica Flohr, Lily Turner, and Sunshine Schneider"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: false
    df_print: kable
---

```{r, echo=FALSE, progress=FALSE, message=FALSE, warning=FALSE}
# Set R Markdown chunk defaults:
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, progress = FALSE,
  fig.width = 16/2, fig.height = 9/2
)
```

# Food Insecurity in the Continental US

Write your blog post here.

```{r}
# Load necessary packages
library(tidyverse)
library(ggplot2)

# Read in ag_productivity.csv
ag_productivity <- read.csv("ag_productivity.csv",
                            stringsAsFactors=FALSE)

# Plot farm output against labor and capital input
ggplot(ag_productivity, aes(x = Year)) +
  labs(title = "US Agricultural Productivity", 
       x = "Year", y = "Change per year") +
  geom_line(aes(y = Total_output, color = "Total farm product output")) +
  geom_line(aes(y = Labor_input_All, color = "Labor input")) +
  geom_line(aes(y = Capital_input_All, color = "Capital input"))
```

```{r}
# Load necessary packages
library(readxl)
library(tidycensus)
library(tidyverse)
library(USAboundaries)
library(maps)
library(sf)
library(leaflet)
library(rgdal)
library(ggplot2)
library(fiftystater)

# Graphing map of food insecure states
# group data by states, including   both food insecure and very food insecure, but only ended up using food insecure data, so I can take that out later

# import Excel data
DTAA2 <- read_xlsx("DTAA2.xlsx")

by_state <- DTAA2 %>%
            group_by(State) %>%
            summarize(mean_insecure = mean(FOODINSEC_13_15),
                      mean_accessibility = mean(PCT_LACCESS_POP15, na.rm = TRUE))

#Creating sf by using data from 'fiftystater' package
sts_as_sf <- st_as_sf(fifty_states, coords = c("long", "lat"))

# convert fifty_states to an sf data frame
states <- (sf_fifty <- st_as_sf(fifty_states, coords = c("long", "lat")) %>% 
   # convert sets of points to polygons
   group_by(id, piece) %>% 
   summarize(do_union = FALSE) %>%
   st_cast("POLYGON") %>%
   # convert polygons to multipolygons for states with discontinuous regions
   group_by(id) %>%
   summarize())
st_crs(sf_fifty) <- 4326

#Changing state names into abbreviations so that I can merge tidycensus data and data I found
sf_fifty$id<- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")

#Joining insecurity data with shape file
sum_state <- sf_fifty%>% 
  inner_join(by_state, by = c("id" = "State"))

#Creating three tiers of insecurity to be reflected on graph
sum_state <- sum_state %>%
  mutate(mean_insecure = cut_number(mean_insecure, 3))
 
#Graphing Insecurity
ggplot() +
  geom_sf(data = sum_state, aes(fill = mean_insecure), size = 0.5) +
  labs(fill = "mean", title = "Food Insecurity")  +
  scale_fill_brewer(palette = "YlOrRd")

#Creating three tiers of accessibility to be reflected on graph
sum_state <- sum_state %>%
  mutate(mean_accessibility = cut_number(mean_accessibility, 3))

#Graphing Accessibility
ggplot() +
  geom_sf(data = sum_state, aes(fill = mean_accessibility), size = 0.5) +
  labs(fill = "mean", title = "Food Accessibility")  +
  scale_fill_brewer(palette = "Greens")

```

