---
title: "More information"
author: "Jessica Flohr, Lily Turner, and Sunshine Schneider"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: false
    df_print: kable
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Set R Markdown chunk defaults:
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, 
  fig.width = 16/2, fig.height = 9/2
)
```

<!--
Comments in HTML are like this! 
-->

```{r}
# Load necessary packages
library(tidyverse)
library(ggplot2)
library(leaflet)
library(sf)
library(leaflet.extras)
library(readxl)
library(maps)
library(rgdal)
library(fiftystater)

# Data import for the leaflet map
farmers_markets <- read.csv("farmers_markets.csv",
                            stringsAsFactors=FALSE)

# Define "support" as how many food assistance programs a market accepts as payment
farmers_markets$support <- farmers_markets$WIC +
  farmers_markets$WICcash + farmers_markets$SFMNP +
  farmers_markets$SNAP
farmers_markets$support <- cut(farmers_markets$support, 
                               breaks=c(-Inf, .9, 1.9, 2.9, 3.9, Inf), 
                 labels=c("0","1","2","3","4"))

# Define "goods" as how many fresh diet essentials  market sells (vegetables, meat, fruits, and grains)
farmers_markets$goods <- farmers_markets$Vegetables +
  farmers_markets$Meat + farmers_markets$Fruits +
  farmers_markets$Grains
farmers_markets$goods <- cut(farmers_markets$goods, 
                               breaks=c(-Inf, .9, 1.9, 2.9, 3.9, Inf), 
                 labels=c("0","1","2","3","4"))

pal <- colorFactor(palette=c("red", "orange", "yellow",
                             "green", "blue"),
                   levels = c("0","1","2","3","4"))

```

# Farmers Markets

```{r}
leaflet(farmers_markets) %>% 
  addProviderTiles("Esri") %>% 
  addCircles(color = ~pal(support), group = "Support Programs") %>%
  addCircles(color = ~pal(goods), group = "Farm Goods") %>%
  addLayersControl(overlayGroups = c("Support", "Farm Goods"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  addLegend(position = "topright",
            pal = pal,
            values = c("0", "1", "2", "3", "4+")) %>%
  addResetMapButton()
```

# Insecurity and Accessibility

```{r}
# Graphing map of food insecure states
# group data by states, including   both food insecure and very food insecure, but only ended up using food insecure data, so I can take that out later

# import Excel data
DTAA2 <- read_xlsx("DTAA2.xlsx")

by_state <- DTAA2 %>%
            group_by(State) %>%
            summarize(mean_insecure = mean(FOODINSEC_13_15),
                      mean_accessibility = mean(PCT_LACCESS_POP15, na.rm = TRUE))

#Creating sf by using data from 'fiftystater' package
sts_as_sf <- st_as_sf(fifty_states, coords = c("long", "lat"))

# convert fifty_states to an sf data frame
states <- (sf_fifty <- st_as_sf(fifty_states, coords = c("long", "lat")) %>% 
   # convert sets of points to polygons
   group_by(id, piece) %>% 
   summarize(do_union = FALSE) %>%
   st_cast("POLYGON") %>%
   # convert polygons to multipolygons for states with discontinuous regions
   group_by(id) %>%
   summarize())
st_crs(sf_fifty) <- 4326

#Changing state names into abbreviations so that I can merge tidycensus data and data I found
sf_fifty$id<- c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY")

#Joining insecurity data with shape file
sum_state <- sf_fifty%>% 
  inner_join(by_state, by = c("id" = "State"))

#Creating three tiers of insecurity to be reflected on graph
sum_state <- sum_state %>%
  mutate(mean_insecure = cut_number(mean_insecure, 3))
 
#Graphing Insecurity
ggplot() +
  geom_sf(data = sum_state, aes(fill = mean_insecure), size = 0.5) +
  labs(fill = "mean", title = "Food Insecurity")  +
  scale_fill_brewer(palette = "YlOrRd")

#Creating three tiers of accessibility to be reflected on graph
sum_state <- sum_state %>%
  mutate(mean_accessibility = cut_number(mean_accessibility, 3))

#Graphing Accessibility
ggplot() +
  geom_sf(data = sum_state, aes(fill = mean_accessibility), size = 0.5) +
  labs(fill = "mean", title = "Food Accessibility")  +
  scale_fill_brewer(palette = "Greens")
```

# State Breakdown

```{r}
# Graphs on percent of farmer's markets that accept various food aid
# Group by state, summarize state data into an average instead of per county

# import Excel file
farm_market <- read_excel("farm.market.xlsx")

# summarize support programs a farmers market accepts
sum_farm_support <- farm_market%>% 
  group_by(State) %>% 
  summarize(mean_SNAP = mean(PCT_FMRKT_SNAP16), 
            mean_WICCASH = mean(PCT_FMRKT_WICCASH16), 
            mean_SFNMP = mean(PCT_FMRKT_SFMNP16), 
            mean_WIC = mean(PCT_FMRKT_WIC16)) 

sum_farm_support[is.na(sum_farm_support)]<-0

# tidy farm support data to be able to make graphs
support_tidy <- gather(data = sum_farm_support, 
                       key = Type,
                       value = Percent,
                       -State)

# plotting graphs
ggplot(support_tidy, aes(x = Type, y = Percent, fill = Type)) +
  geom_col() +
  facet_wrap(~ State) +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank() ,
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

